// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6cHwhLwTWJPfJw7ZNs6r8pK4SlDVwu-g',
    appId: '1:912601771381:web:b7bdbf46f63c7aabceb73c',
    messagingSenderId: '912601771381',
    projectId: 'fund-app-3c2b5',
    authDomain: 'fund-app-3c2b5.firebaseapp.com',
    storageBucket: 'fund-app-3c2b5.appspot.com',
    measurementId: 'G-7W6CRPWRQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTXAnpyGotpbsLqxiTgMetUXBY6TLjdQE',
    appId: '1:912601771381:android:374ca795f8c2a95eceb73c',
    messagingSenderId: '912601771381',
    projectId: 'fund-app-3c2b5',
    storageBucket: 'fund-app-3c2b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX8qmnikAwvo7p0XySEX5X6RMkt_NSaM4',
    appId: '1:912601771381:ios:9ff8a2405d0032d6ceb73c',
    messagingSenderId: '912601771381',
    projectId: 'fund-app-3c2b5',
    storageBucket: 'fund-app-3c2b5.appspot.com',
    iosBundleId: 'com.example.fundApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX8qmnikAwvo7p0XySEX5X6RMkt_NSaM4',
    appId: '1:912601771381:ios:4c094c49fe9b30f6ceb73c',
    messagingSenderId: '912601771381',
    projectId: 'fund-app-3c2b5',
    storageBucket: 'fund-app-3c2b5.appspot.com',
    iosBundleId: 'com.example.fundApp.RunnerTests',
  );
}
